package day4exceptionhandling;
import java.util.Scanner;
public class PersonApp {
public static void main(String[] args) {
	try {
		createperson();
	}
	catch(AgeException e)
	{
		System.out.println(e.getMessage());
	}
	
}
public static  void createperson() throws AgeException
{
	int id;
	String name;
	Personvalidator obj=new Personvalidator();
	Scanner sc=new Scanner(System.in);
	String a=sc.next();
	int age=sc.nextInt();
	boolean res1=obj.validateName(a);

	boolean res2=obj.validateAge(age);
	
	if(res1&&res2)
	{
		System.out.println("enter id");
		id=sc.nextInt();
		System.out.println("enter name");
		name=sc.next();
		System.out.println("enter age");
		age=sc.nextInt();
		Personvalidator obj2=new Personvalidator(id,age,name);
		System.out.println(obj2);
	}
	
		
}
}
